---
sudo: required
language: python

services:
  - docker

python: "2.7"

cache: pip

virtualenv:
  system_site_packages: false

install:
- pip install --upgrade setuptools
- pip install ome-ansible-molecule-dependencies/

script:
# Some roles can't be properly tested in Docker
# These should provide an alternative configuration just for testing syntax
- cd $ROLE
- if [ -f molecule-docker.yml ]; then mv molecule-docker.yml molecule.yml; fi
- ../scripts/test.sh

env:
 - ROLE=ansible-role-selinux-utils
 - ROLE=ansible-role-omero-web
 - ROLE=ansible-role-jekyll-build
 - ROLE=ansible-role-postgresql
 - ROLE=ansible-role-rsync-server
 - ROLE=ansible-role-network
 - ROLE=ansible-role-omero-server
 - ROLE=ansible-role-ice
 - ROLE=ansible-role-lvm-partition
 - ROLE=ansible-role-nginx-proxy
 - ROLE=ansible-role-ssl-certificate
 - ROLE=ansible-role-omero-python-deps
 - ROLE=ansible-role-java
 - ROLE=ansible-role-cli-utils
 - ROLE=ansible-role-analysis-tools
 - ROLE=ansible-role-sudoers
 - ROLE=ansible-role-nginx
 - ROLE=ansible-role-mysql-backup
 - ROLE=ansible-role-logrotate
 - ROLE=ansible-role-nfs-mount
 - ROLE=ansible-role-upgrade-distpackages
 - ROLE=ansible-role-omero-common
 - ROLE=ansible-role-basedeps
 - ROLE=ansible-role-omego
