---
language: python

sudo: required

services:
  - docker

install:
 - pip install --upgrade setuptools
 - pip install ome-ansible-molecule/

script:
 - cd $ROLE && ../scripts/test.sh

env:
 - ROLE=ansible-role-analysis-tools SCENARIO=
 - ROLE=ansible-role-anonymous-ftp SCENARIO=
 - ROLE=ansible-role-basedeps SCENARIO=
 - ROLE=ansible-role-cadvisor SCENARIO=
 - ROLE=ansible-role-cli-utils SCENARIO=
 - ROLE=ansible-role-deploy-archive SCENARIO=
 - ROLE=ansible-role-docker-tools SCENARIO=
 - ROLE=ansible-role-fluentd SCENARIO=
 - ROLE=ansible-role-hosts-populate SCENARIO=
 - ROLE=ansible-role-ice SCENARIO=ice36all
 - ROLE=ansible-role-ice SCENARIO=ice36minimal
 - ROLE=ansible-role-ice SCENARIO=ice36-ubuntu1804
 - ROLE=ansible-role-iptables-raw SCENARIO=
 - ROLE=ansible-role-java SCENARIO=centos
 - ROLE=ansible-role-java SCENARIO=ubuntu
 - ROLE=ansible-role-local-accounts SCENARIO=
 - ROLE=ansible-role-logrotate SCENARIO=
 - ROLE=ansible-role-lvm-partition SCENARIO=
 - ROLE=ansible-role-mysql-backup SCENARIO=
 - ROLE=ansible-role-network-cloud-interfaces SCENARIO=
 - ROLE=ansible-role-network SCENARIO=
 - ROLE=ansible-role-nfs-mount SCENARIO=
 - ROLE=ansible-role-nfs-share SCENARIO=
 - ROLE=ansible-role-nginx-proxy SCENARIO=
 - ROLE=ansible-role-nginx SCENARIO=centos7
 - ROLE=ansible-role-nginx SCENARIO=ubuntu1804
 - ROLE=ansible-role-omego SCENARIO=
 - ROLE=ansible-role-omero-common SCENARIO=
 - ROLE=ansible-role-omero-prometheus-exporter SCENARIO=
 - ROLE=ansible-role-omero-python-deps SCENARIO=
 - ROLE=ansible-role-omero-server SCENARIO=newdep
 - ROLE=ansible-role-omero-server SCENARIO=python3
 - ROLE=ansible-role-omero-server SCENARIO=upgrade-py2py3
 - ROLE=ansible-role-omero-server SCENARIO=upgradetovenv
 - ROLE=ansible-role-omero-user SCENARIO=
 - ROLE=ansible-role-omero-web-django-prometheus SCENARIO=
 - ROLE=ansible-role-omero-web SCENARIO=active
 - ROLE=ansible-role-omero-web SCENARIO=inactive
 - ROLE=ansible-role-omero-web SCENARIO=active-py3-centos7
 - ROLE=ansible-role-omero-web SCENARIO=active-py3-ubuntu1804
 - ROLE=ansible-role-omero-web SCENARIO=py2-py3-upgrade-centos7
 - ROLE=ansible-role-openstack-volume-storage SCENARIO=
 - ROLE=ansible-role-postgresql SCENARIO=
 - ROLE=ansible-role-postgresql-backup SCENARIO=
 - ROLE=ansible-role-prometheus-jmx SCENARIO=
 - ROLE=ansible-role-prometheus-node SCENARIO=
 - ROLE=ansible-role-prometheus-postgres SCENARIO=
 - ROLE=ansible-role-python-pydata SCENARIO=
 - ROLE=ansible-role-reboot-server SCENARIO=
 - ROLE=ansible-role-redis SCENARIO=
 - ROLE=ansible-role-rsync-server SCENARIO=
 - ROLE=ansible-role-samba-client SCENARIO=
 - ROLE=ansible-role-selinux-utils SCENARIO=
 - ROLE=ansible-role-ssl-certificate SCENARIO=
 - ROLE=ansible-role-storage-volume-initialise SCENARIO=
 - ROLE=ansible-role-sudoers SCENARIO=
 - ROLE=ansible-role-system-monitor-agent SCENARIO=
 - ROLE=ansible-role-upgrade-distpackages SCENARIO=
 - ROLE=ansible-role-versioncontrol-utils SCENARIO=
