---
sudo: required
language: python

services:
  - docker

python: "2.7"

cache: pip

virtualenv:
  system_site_packages: false

install:
- pip install --upgrade setuptools
- pip install ome-ansible-molecule-dependencies/

script:
# Some roles can't be properly tested in Docker
# These should provide an alternative configuration just for testing syntax
- cd $ROLE
- if [ -f molecule-docker.yml ]; then mv molecule-docker.yml molecule.yml; fi
- ../scripts/test.sh

env:
 - ROLE=ansible-role-selinux-utils
 - ROLE=ansible-role-omero-web
 - ROLE=ansible-role-postgresql
 - ROLE=ansible-role-nginx-proxy
 - ROLE=ansible-role-network
 - ROLE=ansible-role-omero-server
 - ROLE=ansible-role-jekyll-build
 - ROLE=ansible-role-lvm-partition
 - ROLE=ansible-role-upgrade-distpackages
 - ROLE=ansible-role-rsync-server
 - ROLE=ansible-role-basedeps
 - ROLE=ansible-role-ssl-certificate
 - ROLE=ansible-role-ice
 - ROLE=ansible-role-omego
 - ROLE=ansible-role-omero-python-deps
 - ROLE=ansible-role-java
 - ROLE=ansible-role-fluentd
 - ROLE=ome-ansible-molecule-dependencies
 - ROLE=ansible-role-mysql-backup
 - ROLE=ansible-role-analysis-tools
 - ROLE=ansible-role-cadvisor
 - ROLE=ansible-role-omero-common
 - ROLE=ansible-role-nginx
 - ROLE=ansible-role-prometheus-node
 - ROLE=ansible-role-cli-utils
 - ROLE=ansible-role-sudoers
 - ROLE=ansible-role-prometheus-postgres
 - ROLE=ansible-role-logrotate
 - ROLE=ansible-role-nfs-mount
 - ROLE=ansible-role-omero-web-runtime
 - ROLE=ansible-role-openstack-volume-storage
 - ROLE=ansible-role-debug-dumpallvars
 - ROLE=infrastructure-extract-ansible-role
 - ROLE=ansible-role-redis
 - ROLE=ansible-role-python-pydata
 - ROLE=ansible-role-prometheus-jmx
 - ROLE=ansible-role-local-accounts
 - ROLE=ansible-role-omero-user
 - ROLE=ansible-role-nfs-share
 - ROLE=ansible-role-samba-client
 - ROLE=ansible-role-hosts-populate
 - ROLE=ansible-role-versioncontrol-utils
 - ROLE=ansible-role-reboot-server
 - ROLE=ansible-role-docker-tools
 - ROLE=ansible-role-anonymous-ftp
 - ROLE=ansible-role-storage-volume-initialise
 - ROLE=ansible-role-system-monitor-agent
 - ROLE=ansible-role-network-cloud-interfaces
 - ROLE=ansible-role-docker-slack-notifier
 - ROLE=ansible-role-python-virtualenv-upstream
